NumPy Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

np.int64(8)

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr[0:5] =100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr_copy = arr.copy()

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

2D ARRAY

In [14]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [15]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
arr_2d[0][0]

np.int64(5)

In [23]:
arr_2d[2][1]

np.int64(40)

In [24]:
arr_2d[1,2]

np.int64(30)

In [25]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [26]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

CONDITIONAL SELECTION

In [27]:
arr = np.arange(1,11)

In [28]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
bool_arr =arr> 5

In [31]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [32]:
arr[arr<3]

array([1, 2])

In [33]:
arr_2d = np.arange(50).reshape(5,10)

In [34]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [35]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])