In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [4]:
np.array(my_list)


array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6,],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.random.rand(5)

array([0.65631447, 0.23809242, 0.85320379, 0.56497746, 0.23609149])

In [14]:
np.random.rand(5,5)

array([[0.62371445, 0.95586184, 0.32862401, 0.96395972, 0.93049646],
       [0.16794303, 0.78308088, 0.06251015, 0.36145708, 0.95082648],
       [0.48350584, 0.66983108, 0.26490365, 0.02697999, 0.16997222],
       [0.78112105, 0.84252135, 0.41885932, 0.07737955, 0.91203394],
       [0.19734017, 0.99598445, 0.80767038, 0.0638967 , 0.07226151]])

In [16]:
np.random.randn(4,4)

array([[-0.81457341, -1.62014367,  1.22343462, -0.31086245],
       [-0.00184361, -0.05482858, -0.95080347,  1.40181488],
       [-0.16330045,  0.44172189,  1.40282411, -0.47893692],
       [-0.02329363, -0.56694398,  0.27500533,  0.46128928]])

In [20]:
np.random.randint(1,100,10)

array([83,  8, 60, 12, 80, 82, 62, 96, 30, 21], dtype=int32)

In [21]:
arr = np.arange(25)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr = np.random.randint(0,50,10)

In [24]:
ranarr

array([27, 24, 20,  8, 14, 33, 23, 36, 16, 25], dtype=int32)

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
ranarr.max()

np.int32(36)

In [28]:
ranarr.min()

np.int32(8)

In [29]:
ranarr.argmax()

np.int64(7)

In [30]:
ranarr.argmin()

np.int64(3)

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
arr.dtype

dtype('int64')