In [1]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [8]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [10]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [11]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.random.rand(1)

array([0.06687739])

In [14]:
np.random.randn(25)

array([-1.0197528 ,  0.74702468,  1.16240005,  0.05371321, -0.23852938,
        0.31665392,  0.56086399,  0.7514547 , -0.64372611,  0.75855686,
       -0.10447066, -0.34133416,  3.24191937,  0.69017569, -2.86976955,
        0.3181146 ,  0.70383967,  0.39224117, -0.07541402, -1.66584779,
        0.44157379, -0.00915507, -0.68499179, -1.44598577, -0.32770205])

In [17]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [18]:
np.linspace(0.1,20)

array([ 0.1       ,  0.50612245,  0.9122449 ,  1.31836735,  1.7244898 ,
        2.13061224,  2.53673469,  2.94285714,  3.34897959,  3.75510204,
        4.16122449,  4.56734694,  4.97346939,  5.37959184,  5.78571429,
        6.19183673,  6.59795918,  7.00408163,  7.41020408,  7.81632653,
        8.22244898,  8.62857143,  9.03469388,  9.44081633,  9.84693878,
       10.25306122, 10.65918367, 11.06530612, 11.47142857, 11.87755102,
       12.28367347, 12.68979592, 13.09591837, 13.50204082, 13.90816327,
       14.31428571, 14.72040816, 15.12653061, 15.53265306, 15.93877551,
       16.34489796, 16.75102041, 17.15714286, 17.56326531, 17.96938776,
       18.3755102 , 18.78163265, 19.1877551 , 19.59387755, 20.        ])

In [19]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [21]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [22]:
mat[3][4]

np.int64(20)

In [24]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [25]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [26]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [27]:
np.sum(mat)

np.int64(325)

In [28]:
np.std(mat)

np.float64(7.211102550927978)

In [29]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])